# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAPI', '0004_auto_20180914_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
